### ISSUE TITLE
Executable not found in $PATH

### ISSUE THREAD

**Issue by buehler** [pandoc/pandoc-action-example#15]
When using the docker action of pandoc the following error occurs:

```yaml
      - run: |
          mkdir public
          echo "FILELIST=$(printf '"%s" ' src/sections/*.md)" >> $GITHUB_ENV
      - name: Build Report to HTML
        uses: docker://pandoc/latex:2.11.4
        with:
          args: >-
            pandoc
            --filter pandoc-xnos
            --metadata-file=src/metadata.yaml
            --citeproc
            --bibliography=src/bibliography.bib
            --toc
            --standalone
            --output=public/index.html
            ${{ env.FILELIST }}
```

```
←[34m[Publish GitHub Pages/build-gh-pages ] ←[0m  ❌  Failure - Build Report to HTML
Error: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--filter": executable file not found in $PATH: unknown
```

The problem seems to be that the `ENTRYPOINT` is not set anymore?

(note that pandoc-xnos is installed via PIP)

**Comment by buehler** [comment]
Now I ruled out that it is not the docker image. with `act`, the image does not run. Online the issue is, that the pandoc-xnos is not found nontheless.

**Comment by alerque** [comment]
This isn't an issue with the *Action* setup. The Docker image you are using doesn't have that filter baked in anywhere.

Have you seen [building custom images](https://github.com/pandoc/dockerfiles#building-custom-images)? I think what you're going to need is a small shim Dockerfile in your projcet repository that loads the Pandoc image you want to use then adds the [pandoc-xnos](https://github.com/tomduck/pandoc-xnos) filter that you would like to use to the image in an appropriate place. Then you can use *that* in your GitHub Action workflow.

It would probably be a good idea to include an example of doing that properly the documentation for this repository.

**Comment by buehler** [comment]
That's a nice idea! I'm trying it out and if it works, I'm going to open a PR to add the example here.

**Comment by alerque** [comment]
Another solution that would work would be to use a container arrangement like in #11, but add a step that installs your filters to the container before using Pandoc. I don't think that's quite as well suited to solve this particular issue, but maybe worth mentioning in case other people with similar but not identical issues come by.

**Comment by buehler** [comment]
To be fair, what I already tried was:
```yaml
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandoc-fignos pandoc-tablenos pandoc-secnos
      - run: |
          mkdir public
          echo "FILELIST=$(printf '"%s" ' src/sections/*.md)" >> $GITHUB_ENV
      - name: Build Report to HTML
        uses: docker://pandoc/latex:2.11.4
        with:
          args: >-
            --filter pandoc-xnos
            --metadata-file=src/metadata.yaml
            --citeproc
            --bibliography=src/bibliography.bib
            --toc
            --standalone
            --output=public/index.html
            ${{ env.FILELIST }}
```

So I basically installed python, pip and the executables. But it seems that they are not transferred into the docker execution.
