### ISSUE TITLE
Missing package 

### ISSUE THREAD

**Issue by gvolpe** [pandoc/pandoc-action-example#2]
Hi, 

I'm trying to use this GH action but I'm currently running into the following issue:

```bash
Error producing PDF.
! LaTeX Error: File `tcolorbox.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.141 \newtcolorbox

##[error]Docker run failed with exit code 43
```

The `tcolorbox` package is in `texlive-latex-extra`. I even tried to install this manually and I can verify this package is installed in my action:

```yaml
- name: Install extra LaTeX packages
  run: sudo apt-get -y install texlive-latex-extra
- name: Show package
  run: apt-cache search tcolorbox | grep tex
```

Even when the package is installed in the system, I still get this error. Any ideas?

PS. Using `pandoc/latex:2.7`

**Comment by gvolpe** [comment]
Upgraded to the `2.8` version and now I get this error:

```bash
Error producing PDF.
! LaTeX Error: File `grffile.sty' not found.
```

**Comment by gvolpe** [comment]
Upgraded to the `2.9` version and I get the same error as with `2.7`.

**Comment by gvolpe** [comment]
I fixed it on my end by not using the `pandoc/latex` image. Instead, I installed everything I need:

```yaml
runs-on: ubuntu-latest
    steps:
      - name: Install LaTeX packages
        run: sudo apt-get -y install texlive-base texlive-latex-extra texlive-fonts-extra
      - name: Download Pandoc
        run: wget -c https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
      - name: Install Pandoc
        run: sudo dpkg -i pandoc-2.7.3-1-amd64.deb
      - uses: actions/checkout@v2
```
