### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by vlc1** [pandoc/pandoc-action-example#20]
Hi there,

I'm currently using Pandoc's docker in a Github action and it's working really well, thanks a lot for providing this opportunity!

I'm currently converting a single markdown file into latex using something like this :
```yaml
- name: Pandoc
  uses: docker://pandoc/core:2.9
  with:
    args: >-
      -s -N
      -f markdown
      -t latex
      -o foo.tex
      foo.md
```

I would like to do this for multiple files, i. e. convert bar.md to bar.tex, baz.md to bar.tex and so forth and so on.

I tried the following but Github is complaining about the sequence...
```yaml
- name: Pandoc
  uses: docker://pandoc/core:2.9
  with:
    args:
      - -s -N -f markdown -t latex -o foo.tex foo.md
      - -s -N -f markdown -t latex -o bar.tex bar.md
```

Any pointers on how I could do this would be greatly appreciated! Thanks a lot!
