### ISSUE TITLE
Cache the pulled Docker image with GHA?

### ISSUE THREAD

**Issue by firasm** [pandoc/pandoc-action-example#23]
First of all, thanks for creating these examples, they've been a Godsend for me! Much appreciated.

This may be beyond the scope of this project, but is there a way to cache the pulled docker images within a GitHub Action?

I am trying to cut down on the run-time of my github action, and everything is very fast, except the initial step of pulling the docker image - which takes ~55% of the total time. Ideally the first time it would take the full time, and then subsequently, it would use a cached Docker image.

<img width="450" alt="Screen Shot 2022-02-19 at 10 18 03 PM" src="https://user-images.githubusercontent.com/2507459/154831115-dcf48e2c-7f20-4726-9cf7-142aef5eda3c.png">

I have been trying to read up about this, and it sounds like there is some new functionality added that makes this possible, but my attempts to make it worked haven't yielded much fruit.

## Some references

- [Here is the most promising source about this](https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching)
- 
Adding this to my GHA *should* work, but I don't think I've got the placement quite right:

```
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
```
- [Another GHA that claims to cache](https://github.com/marketplace/actions/docker-layer-caching) (untested)
- [A potential lead](https://github.community/t/cache-pulled-docker-images-already-built-and-published/17753/6)

Let me know if I can provide any more information
