### ISSUE TITLE
Error: pdflatex not found

### ISSUE THREAD

**Issue by anirbanbasu** [pandoc/pandoc-action-example#24]
I have the following GitHub work flow as a test and it fails, with the error `pdflatex not found` when invoked using `act workflow_dispatch --container-architecture=linux/amd64`.

```
name: Compile PDF

on: workflow_dispatch

jobs:
  compile_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Copy content from repository
        uses: actions/checkout@v3
      - name: Prepare files
        run: |
          mkdir -p output
      - name: Compile PDF
        uses: docker://pandoc/latex:latest
        with:
           args: --output=output/test.pdf README.md
      - name: Copy output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/test.pdf
```

The detailed error is:
```
docker run image=pandoc/latex:latest platform=linux/amd64 entrypoint=[] cmd=["--output=output/test.pdf" "README.md"]
| pdflatex not found. Please select a different --pdf-engine or install pdflatex
```

However, it runs totally fine if I invoke `pandoc` using Docker as:
```
docker run --platform "linux/amd64" --rm --volume "$(pwd):/data" --user $(id -u):$(id -g) pandoc/latex:latest README.md --output=output/test.pdf
```

I am baffled. Am I missing something pretty simple, or is this an issue with `act`?
