### ISSUE TITLE
How to run pandoc using a Windows runner?

### ISSUE THREAD

**Issue by slavistan** [pandoc/pandoc-action-example#25]
Hi. I'm forced to use a Windows runner for a pipeline and the instructions in this repository do not work. Here's a MWE:

This pipeline fails, producing the error message `Value cannot be null. (Parameter 'container')`.

```
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: docker://pandoc/core
        with:
          args: "--help"
```

Changing to the `ubuntu-latest` runner fixes the problem. Any idea on why this is the case?

**Comment by slavistan** [comment]
Turn out, installing via chocolatey does the job.

```
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: |
          choco install --yes pandoc
          pandoc --help
```

That'd be something to put into the README.
