### ISSUE TITLE
obstacle replicating example "long usage"

### ISSUE THREAD

**Issue by nbehrnd** [pandoc/pandoc-action-example#27]
Do difficulties I observe correlate with the red indicators "failing" on the landing page?

To familiarize myself with GitHub actions in general, and their use with pandoc in particular, I set up "Long Pandoc Calls" in a new GitHub repository in a path of `.github/workflows/pandoc_long_call.yml`.  To account for developments on side of pandoc and ubuntu, the content however was edited a little and now reads as

```yaml
name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/core:3.1
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=index.html
            input.txt
```

Contrasting to my anticipation, there however is no new (i.e. previously absent) file `index.html` written one could retrieve from the repository.  I assumed `input.txt` would be a new file deposit in the top directory of the GitHub repository; this however equally doesn't show up.

Do you recommend a different syntax or/and an additional instruction to your example snippet to retain the new file as permanent record of `index.html`?  If I want pandoc to convert some files within such a GitHub action, does `args` function as if pandoc were at the top level/root of the repository?
