### ISSUE TITLE
Is it possible to define custom templates?

### ISSUE THREAD

**Issue by El-Don-Quijote** [pandoc/pandoc-action-example#36]
I am using this github action to create a latex file from a markdown file and am wondering if it is possible to bring a custom template, e.g. `template.tex` along? Or would I need to have my own Docker image, where `template.tex` is included? Thanks!

**Comment by tarleb** [comment]
It should be possible to use the template with something like

``` yaml
      - uses: docker://pandoc/core:3.3
        with:
          args: >- 
            --template=./path/to/template.tex
            # rest of command
```
