### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by maxrobot** [pandoc/pandoc-action-example#7]
Chaps, 

In the readme for the long example,

```
name: Long Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "foo" > input.txt  # create an example file
      - uses: docker://pandoc/core:2.9
        with:
          args: |>  # allows you to break string into multiple lines
            --standalone
            --output=index.html
            input.txt
```

I believe `args: |>` should be `args: >-`.
