### ISSUE TITLE
Add support for choosing working directory

### ISSUE THREAD

**Issue by AndyClifton** [pandoc/pandoc-action-example#8]
I'm trying to implement an action to use pandoc on markdown files in my repository. The files are in subdirectories, e.g.,

```basj
. repo
  ├──seminar1
      ├──slides.md
  ├──seminar2
      ├── slides.md
```

I cannot figure out how to set the working directory for pandoc. Currently my action looks like this:

``` yml
name: Make seminar slides from markdown

on: push
defaults:
  run:
    working-directory: seminar1

jobs:
  make_seminar1_slides:
    runs-on: ubuntu-18.04
    steps:
      - name: Get files
        uses: actions/checkout@v2
        with:
          ref: slides
          
      - name: Load pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: --from=gfm --to=beamer --resource-path=seminar1 --output=seminar1/slides.md.pdf seminar1/slides.md
          
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: seminar-slides
          path: slides.md.pdf
```

Am I missing something? Is there a way to set a working directory for pandoc or in the action?

**Comment by AndyClifton** [comment]
This action seems to work if I modify the _upload_ part of the action to explicitly include the directory information.

```yml
name: Make seminar slides from markdown

on: push
defaults:
  run:
    working-directory: seminar1

jobs:
  make_seminar1_slides:
    runs-on: ubuntu-18.04
    steps:
      - name: Get files
        uses: actions/checkout@v2
        with:
          ref: slides
          
      - name: Load pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: --from=markdown --to=beamer --resource-path=seminar1 --output=seminar1/slides.md.pdf seminar1/slides.md
          
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: seminar-slides
          path: seminar1/slides.md.pdf
```

I'm not sure that there's a solution here that can be implemented by / using Pandoc; instead it looks like the `uses` action could do with some updating to get the working directory.
